version: "3.9"  # optional since v1.27.0
services:
  build:
    build: .
    container_name: IronswornCompanion
    entrypoint: sh -c "cd /app && npm run build"
    volumes:
      - ./:/app
    environment:
      - PUBLIC_URL=${PUBLIC_URL:-}
      - GAME_RULES=${GAME_RULES:-}
  start:
    build: .
    container_name: IronswornCompanion
    entrypoint: sh -c 'cd /app && npm run start'
    ports:
      - "3010:3010"
    volumes:
      - ./:/app
    environment:
      - REACT_APP_GAME_RULES=${GAME_RULES:-} # default to empty string
      - GAME_RULES=${GAME_RULES:-}
  setup:
    build: .
    container_name: IronswornCompanion
    entrypoint: sh -c 'cd /app && npm run setup'
    volumes:
      - ./:/app
  clean:
    build: .
    container_name: IronswornCompanion
    entrypoint: sh -c 'cd /app && npm run clean'
    volumes:
      - ./:/app
