const foes = [
  {
    Name: "Broken",
    Tags: [
      "marine",
      "pass",
      "shadowfen",
      "subterranean",
      "tanglewood",
      "corrupted",
      "sentient",
      "squatter",
      "plains",
      "wastes",
    ],
    id: "core-foe-ironlanders-broken",
    Type: "Ironlanders",
  },
  {
    Name: "Common Folk",
    Tags: ["sentient", "squatter"],
    id: "core-foe-ironlanders-common-folk",
    Type: "Ironlanders",
  },
  {
    Name: "Hunter",
    Tags: ["marine", "pass", "shadowfen", "tanglewood", "wild", "sentient", "squatter", "plains", "wastes"],
    id: "core-foe-ironlanders-hunter",
    Type: "Ironlanders",
  },
  {
    Name: "Mystic",
    Tags: [
      "marine",
      "pass",
      "shadowfen",
      "subterranean",
      "tanglewood",
      "corrupted",
      "faithful",
      "remnant",
      "sentient",
      "squatter",
      "plains",
      "wastes",
    ],
    id: "core-foe-ironlanders-mystic",
    Type: "Ironlanders",
  },
  {
    Name: "Raider",
    Tags: ["marine", "pass", "shadowfen", "subterranean", "tanglewood", "sentient", "squatter", "plains", "wastes"],
    id: "core-foe-ironlanders-raider",
    Type: "Ironlanders",
  },
  {
    Name: "Warrior",
    Tags: ["marine", "pass", "shadowfen", "subterranean", "tanglewood", "faithful", "sentient", "plains", "wastes"],
    id: "core-foe-ironlanders-warrior",
    Type: "Ironlanders",
  },
  {
    Name: "Husk",
    Tags: [
      "marine",
      "pass",
      "shadowfen",
      "subterranean",
      "tanglewood",
      "corrupted",
      "sentient",
      "squatter",
      "plains",
      "wastes",
    ],
    id: "core-foe-ironlanders-husk",
    Type: "Ironlanders",
  },
  {
    Name: "Zealot",
    Tags: [
      "marine",
      "pass",
      "shadowfen",
      "subterranean",
      "tanglewood",
      "faithful",
      "remnant",
      "sentient",
      "squatter",
      "plains",
      "wastes",
    ],
    id: "core-foe-ironlanders-zealot",
    Type: "Ironlanders",
  },
  {
    Name: "Elf",
    Tags: ["tanglewood", "wild", "sentient"],
    id: "core-foe-firstborn-elf",
    Type: "Firstborn",
  },
  {
    Name: "Giant",
    Tags: ["pass", "wild", "sentient", "wastes"],
    id: "core-foe-firstborn-giant",
    Type: "Firstborn",
  },
  {
    Name: "Primordial",
    Tags: ["arctic", "marine", "pass", "shadowfen", "tanglewood", "wild", "flying", "plains", "wastes"],
    id: "core-foe-firstborn-primordial",
    Type: "Firstborn",
  },
  {
    Name: "Troll",
    Tags: ["shadowfen", "wild", "sentient", "DEVEL_freshwater"],
    id: "core-foe-firstborn-troll",
    Type: "Firstborn",
  },
  {
    Name: "Varou",
    Tags: ["tanglewood", "wild", "sentient"],
    id: "core-foe-firstborn-varou",
    Type: "Firstborn",
  },
  {
    Name: "Atanya",
    Tags: ["arctic", "marine", "wild", "sentient"],
    id: "core-foe-firstborn-atanya",
    Type: "Firstborn",
  },
  {
    Name: "Merrow",
    Tags: ["marine", "shadowfen", "faithful", "wild", "remnant", "sentient"],
    id: "core-foe-firstborn-merrow",
    Type: "Firstborn",
  },
  {
    Name: "Bear",
    Tags: ["arctic", "pass", "shadowfen", "tanglewood", "wild", "squatter", "plains", "wastes"],
    id: "core-foe-animal-bear",
    Type: "Animal",
  },
  {
    Name: "Boar",
    Tags: ["shadowfen", "tanglewood", "wild", "squatter", "plains"],
    id: "core-foe-animal-boar",
    Type: "Animal",
  },
  {
    Name: "Gaunt",
    Tags: ["tanglewood", "wild"],
    id: "core-foe-animal-gaunt",
    Type: "Animal",
  },
  {
    Name: "Marsh Rat",
    Tags: ["shadowfen", "vermin", "wild"],
    id: "core-foe-animal-marsh-rat",
    Type: "Animal",
  },
  {
    Name: "Wolf",
    Tags: ["arctic", "pass", "shadowfen", "tanglewood", "wild", "squatter", "plains", "wastes"],
    id: "core-foe-animal-wolf",
    Type: "Animal",
  },
  {
    Name: "Bladewing",
    Tags: ["pass", "shadowfen", "subterranean", "vermin", "wild", "squatter", "flying", "plains", "wastes"],
    id: "core-foe-animal-bladewing",
    Type: "Animal",
  },
  {
    Name: "Carrion Newt",
    Tags: ["shadowfen", "subterranean", "vermin", "wild", "DEVEL_freshwater"],
    id: "core-foe-animal-carrion-newt",
    Type: "Animal",
  },
  {
    Name: "Cave Lion",
    Tags: ["pass", "subterranean", "tanglewood", "wild", "squatter", "wastes"],
    id: "core-foe-animal-cave-lion",
    Type: "Animal",
  },
  {
    Name: "Deep Rat",
    Tags: ["subterranean", "vermin", "wild", "squatter"],
    id: "core-foe-animal-deep-rat",
    Type: "Animal",
  },
  {
    Name: "Nightmare Spider",
    Tags: ["subterranean", "tanglewood", "vermin", "wild", "squatter"],
    id: "core-foe-animal-nightmare-spider",
    Type: "Animal",
  },
  {
    Name: "Shroud Crab",
    Tags: ["marine", "vermin", "wild"],
    id: "core-foe-animal-shroud-crab",
    Type: "Animal",
  },
  {
    Name: "Trog",
    Tags: ["subterranean", "vermin", "wild"],
    id: "core-foe-animal-trog",
    Type: "Animal",
  },
  {
    Name: "Basilisk",
    Tags: ["shadowfen", "vermin", "wild", "DEVEL_freshwater"],
    id: "core-foe-beast-basilisk",
    Type: "Beast",
  },
  {
    Name: "Elder Beast",
    Tags: ["arctic", "marine", "pass", "shadowfen", "subterranean", "tanglewood", "wild", "flying", "plains"],
    id: "core-foe-beast-elder-beast",
    Type: "Beast",
  },
  {
    Name: "Harrow Spider",
    Tags: ["tanglewood", "vermin", "wild"],
    id: "core-foe-beast-harrow-spider",
    Type: "Beast",
  },
  {
    Name: "Leviathan",
    Tags: ["marine", "wild"],
    id: "core-foe-beast-leviathan",
    Type: "Beast",
  },
  {
    Name: "Mammoth",
    Tags: ["wild", "plains", "wastes"],
    id: "core-foe-beast-mammoth",
    Type: "Beast",
  },
  {
    Name: "Wyvern",
    Tags: ["marine", "pass", "tanglewood", "vermin", "wild", "flying", "plains", "wastes"],
    id: "core-foe-beast-wyvern",
    Type: "Beast",
  },
  {
    Name: "Chitter",
    Tags: ["subterranean", "vermin", "wild", "squatter"],
    id: "core-foe-beast-chitter",
    Type: "Beast",
  },
  {
    Name: "Gnarl",
    Tags: ["tanglewood", "wild"],
    id: "core-foe-beast-gnarl",
    Type: "Beast",
  },
  {
    Name: "Iron-Wracked Beast",
    Tags: [
      "arctic",
      "marine",
      "pass",
      "shadowfen",
      "subterranean",
      "tanglewood",
      "vermin",
      "corrupted",
      "wild",
      "flying",
      "plains",
      "wastes",
    ],
    id: "core-foe-beast-iron-wracked-beast",
    Type: "Beast",
  },
  {
    Name: "Kraken",
    Tags: ["marine", "wild"],
    id: "core-foe-beast-kraken",
    Type: "Beast",
  },
  {
    Name: "Nightspawn",
    Tags: [
      "arctic",
      "marine",
      "pass",
      "shadowfen",
      "subterranean",
      "tanglewood",
      "vermin",
      "corrupted",
      "faithful",
      "wild",
      "remnant",
      "squatter",
      "flying",
      "plains",
      "wastes",
    ],
    id: "core-foe-beast-nightspawn",
    Type: "Beast",
  },
  {
    Name: "Rhaskar",
    Tags: ["arctic", "marine", "wild"],
    id: "core-foe-beast-rhaskar",
    Type: "Beast",
  },
  {
    Name: "Wyrm",
    Tags: ["subterranean", "tanglewood", "wild"],
    id: "core-foe-beast-wyrm",
    Type: "Beast",
  },
  {
    Name: "Bonewalker",
    Tags: ["arctic", "pass", "shadowfen", "subterranean", "tanglewood", "corrupted", "undead", "plains", "wastes"],
    id: "core-foe-horror-bonewalker",
    Type: "Horror",
  },
  {
    Name: "Frostbound",
    Tags: ["arctic", "pass", "remnant", "undead", "wastes"],
    id: "core-foe-horror-frostbound",
    Type: "Horror",
  },
  {
    Name: "Chimera",
    Tags: [
      "arctic",
      "marine",
      "pass",
      "shadowfen",
      "subterranean",
      "tanglewood",
      "vermin",
      "corrupted",
      "flying",
      "plains",
      "wastes",
    ],
    id: "core-foe-horror-chimera",
    Type: "Horror",
  },
  {
    Name: "Haunt",
    Tags: [
      "arctic",
      "marine",
      "pass",
      "shadowfen",
      "subterranean",
      "tanglewood",
      "remnant",
      "sentient",
      "squatter",
      "undead",
      "plains",
      "wastes",
    ],
    id: "core-foe-horror-haunt",
    Type: "Horror",
  },
  {
    Name: "Hollow",
    Tags: ["tanglewood", "wild", "sentient", "undead"],
    id: "core-foe-horror-hollow",
    Type: "Horror",
  },
  {
    Name: "Iron Revenant",
    Tags: [
      "arctic",
      "marine",
      "pass",
      "shadowfen",
      "subterranean",
      "tanglewood",
      "faithful",
      "remnant",
      "sentient",
      "undead",
      "plains",
      "wastes",
    ],
    id: "core-foe-horror-iron-revenant",
    Type: "Horror",
  },
  {
    Name: "Sodden",
    Tags: ["marine", "shadowfen", "remnant", "sentient", "undead", "DEVEL_freshwater"],
    id: "core-foe-horror-sodden",
    Type: "Horror",
  },
  {
    Name: "Blighthound",
    Tags: ["arctic", "pass", "shadowfen", "subterranean", "tanglewood", "corrupted", "plains", "wastes"],
    id: "core-foe-horror-blighthound",
    Type: "Horror",
  },
  {
    Name: "Bog Rot",
    Tags: ["shadowfen", "corrupted", "remnant", "sentient", "undead"],
    id: "core-foe-horror-bog-rot",
    Type: "Horror",
  },
  {
    Name: "Bonehorde",
    Tags: ["pass", "shadowfen", "subterranean", "tanglewood", "corrupted", "remnant", "undead", "plains", "wastes"],
    id: "core-foe-horror-bonehorde",
    Type: "Horror",
  },
  {
    Name: "Thrall",
    Tags: [
      "marine",
      "pass",
      "shadowfen",
      "subterranean",
      "tanglewood",
      "remnant",
      "sentient",
      "squatter",
      "undead",
      "plains",
      "wastes",
    ],
    id: "core-foe-horror-thrall",
    Type: "Horror",
  },
  {
    Name: "Wight",
    Tags: [
      "arctic",
      "marine",
      "pass",
      "shadowfen",
      "subterranean",
      "tanglewood",
      "faithful",
      "remnant",
      "sentient",
      "squatter",
      "undead",
      "plains",
      "wastes",
    ],
    id: "core-foe-horror-wight",
    Type: "Horror",
  },
  {
    Name: "Blood Thorn",
    Tags: ["tanglewood", "wild", "immobile"],
    id: "core-foe-anomaly-blood-thorn",
    Type: "Anomaly",
  },
  {
    Name: "Circle of Stones",
    Tags: ["pass", "shadowfen", "tanglewood", "remnant", "sentient", "immobile", "plains", "wastes"],
    id: "core-foe-anomaly-circle-of stones",
    Type: "Anomaly",
  },
  {
    Name: "Glimmer",
    Tags: [
      "arctic",
      "marine",
      "pass",
      "shadowfen",
      "subterranean",
      "tanglewood",
      "corrupted",
      "sentient",
      "plains",
      "wastes",
    ],
    id: "core-foe-anomaly-glimmer",
    Type: "Anomaly",
  },
  {
    Name: "Gloom",
    Tags: ["shadowfen", "subterranean", "tanglewood", "corrupted", "flying"],
    id: "core-foe-anomaly-gloom",
    Type: "Anomaly",
  },
  {
    Name: "Maelstrom",
    Tags: ["marine", "subterranean", "wild", "remnant"],
    id: "core-foe-anomaly-maelstrom",
    Type: "Anomaly",
  },
  {
    Name: "Tempest",
    Tags: ["arctic", "marine", "pass", "shadowfen", "tanglewood", "flying", "plains", "wastes"],
    id: "core-foe-anomaly-tempest",
    Type: "Anomaly",
  },
];

export default foes;
